# Generated by Django 4.0.1 on 2022-03-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao_curta', models.TextField(max_length=255, verbose_name='Descrição Curta')),
                ('descricao_longa', models.TextField(verbose_name='Descrição Longa')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('preco_marketing', models.FloatField(blank=True, editable=False, null=True, verbose_name='Preço (R$)')),
                ('preco_marketing_promocional', models.FloatField(blank=True, editable=False, null=True, verbose_name='Preço Promocional (R$)')),
                ('disponivel', models.BooleanField(default=False, editable=False, verbose_name='Disponível?')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preco', models.FloatField(default=0, verbose_name='Preço (R$)')),
                ('preco_promocional', models.FloatField(blank=True, null=True, verbose_name='Preço Promocional (R$)')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
