# Generated by Django 4.0.1 on 2022-03-25 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('total', models.FloatField(verbose_name='Valor Total (R$)')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Total de Itens')),
                ('status', models.CharField(choices=[('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado')], default='C', max_length=1, verbose_name='Status')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produto', models.PositiveIntegerField(verbose_name='ID do Produto')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('id_variacao', models.PositiveIntegerField(verbose_name='ID da Variação do Produto')),
                ('nome_variacao', models.CharField(max_length=50, verbose_name='Nome da Variação do Produto')),
                ('preco', models.FloatField(verbose_name='Preço (R$)')),
                ('preco_promocional', models.FloatField(blank=True, null=True, verbose_name='Preço Promocional (R$)')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('imagem', models.CharField(max_length=2000, verbose_name='Caminho da Imagem')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Itens de pedido',
            },
        ),
    ]
