# Generated by Django 4.0.1 on 2022-02-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produto', models.PositiveIntegerField(verbose_name='ID do Produto')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('id_variacao', models.PositiveIntegerField(verbose_name='ID da Variação do Produto')),
                ('nome_variacao', models.CharField(max_length=50, verbose_name='Nome da Variação do Produto')),
                ('preco', models.FloatField(verbose_name='Preço (R$)')),
                ('preco_promocional', models.FloatField(blank=True, null=True, verbose_name='Preço Promocional (R$)')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('imagem', models.CharField(max_length=2000, verbose_name='Caminho da Imagem')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
