# Generated by Django 4.0.1 on 2022-02-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_itempedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item de pedido', 'verbose_name_plural': 'Itens de pedido'},
        ),
    ]
